<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_menu().
 */
function ymb_menu() {
  $items['admin/structure/block/add-ymb-block'] = array(
    'title' => 'Add new Yandex Money Block',
    'description' => 'Create block with form to raise money to your Yandex Money Wallet.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ymb_block_add_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/structure/block/delete-ymb-block'] = array(
    'title' => 'Delete block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ymb_block_delete_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme()
 */
function ymb_theme() {
  return array(
    'ymb_form' => array(
      'variables' => array('ymb_form' => NULL),
      'template' => 'ymb-form',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function ymb_block_info() {
  $blocks = array();
  $bids = ymb_block_get_bids();

  foreach ($bids as $bid) {
    $blocks[$bid] = array(
      'info' => t('Yandex Money Block') . ': ' . $bid,
      'cache' => DRUPAL_NO_CACHE,
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ymb_block_view($delta = '') {
  $ymb_form = ymb_block_get($delta);

  $block = array(
    'subject' => NULL,
    'content' => array(
      '#markup' => theme('ymb_form', array('ymb_form' => $ymb_form)),
    ),
  );

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function ymb_block_configure($delta = '')
{
  $ymb_block = ymb_block_get($delta);

  return ymb_block_form($ymb_block);
}

function ymb_block_save($delta = '', $edit = array()) {
  ymb_block_update($edit, $delta);
}

function ymb_block_add_form($form, &$form_state) {
  $ymb_block = ymb_block_get();
  $form = ymb_block_form($ymb_block);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function ymb_block_add_form_submit($form, &$form_state) {
  $bid = ymb_block_create($form_state['values']);
  $form_state['redirect'] = 'admin/structure/block/manage/ymb/'. $bid .'/configure';
}

function ymb_block_form($ymb_block) {
  $form = array();

  $form['receiver'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Yandex Money Wallet'),
    '#default_value' => $ymb_block['receiver'],
    '#maxlength' => 17,
    '#required' => TRUE,
    '#element_validate' => array('element_validate_number'),
  );

  $form['target'] = array(
    '#type' => 'textfield',
    '#title' => t('Payment purpose'),
    '#default_value' => $ymb_block['target'],
    '#required' => TRUE,
  );

  $form['sum'] = array(
    '#type' => 'textfield',
    '#title' => t('Amount to be prompted'),
    '#default_value' => $ymb_block['sum'],
    '#required' => TRUE,
    '#maxlength' => 4,
    '#element_validate' => array('element_validate_number'),
  );

  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('Link for redirecting'),
    '#default_value' => $ymb_block['url'],
  );

  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $ymb_block['description'],
  );

  return $form;
}

function ymb_block_delete_form($form, &$form_state, $delta) {
  $block = block_load('ymb', $delta);

  $form['info'] = array('#type' => 'hidden', '#value' => $block->title);
  $form['bid'] = array('#type' => 'hidden', '#value' => $block->delta);

  return confirm_form(
    $form,
    t('Are you sure you want to delete the block %name?', array('%name' => $block->title)),
    'admin/structure/block',
    '',
    t('Delete'),
    t('Cancel')
  );
}

function ymb_block_delete_form_submit($form, &$form_state) {
  $bid = $form_state['values']['bid'];
  ymb_block_delete($bid);
  drupal_set_message(t('The block %name has been removed.', array('%name' => $form_state['values']['info'])));
  cache_clear_all();
  $form_state['redirect'] = 'admin/structure/block';
}

function ymb_block_get($bid = NULL) {
  $ymb_block = db_select('ymb', 'n')
    ->fields('n')
    ->condition('n.bid', $bid)
    ->execute()
    ->fetchAssoc();

  if (!$ymb_block) {
    $ymb_block = array(
      'bid' => '',
      'receiver' => '',
      'target' => '',
      'sum' => '',
      'url' => '',
      'description' => '',
    );
  }

  return $ymb_block;
}

function ymb_block_get_bids() {
  return db_select('ymb', 'n')
    ->fields('n', array('bid'))
    ->execute()
    ->fetchCol();
}

function ymb_block_update($data, $bid) {
  db_update('ymb')
    ->fields(array(
      'receiver' => $data['receiver'],
      'target' => $data['target'],
      'sum' => $data['sum'],
      'url' => $data['url'],
      'description' => $data['description'],
    ))
    ->condition('bid', $bid)
    ->execute();
}

function ymb_block_create($data) {
  return db_insert('ymb')
    ->fields(array(
      'receiver' => $data['receiver'],
      'target' => $data['target'],
      'sum' => $data['sum'],
      'url' => $data['url'],
      'description' => $data['description'],
    ))
    ->execute();
}

function ymb_block_delete($bid) {
  db_delete('ymb')
    ->condition('bid', $bid)
    ->execute();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function ymb_form_block_admin_display_form_alter(&$form, &$form_state) {
  $bids = ymb_block_get_bids();

  foreach ($bids as $bid) {
    $form['blocks']['ymb_' . $bid]['delete'] = array(
      '#type' => 'link',
      '#title' => t('delete'),
      '#href' => 'admin/structure/block/delete-ymb-block/' . $bid,
    );
  }
}

/**
 * Implements hook_preprocess_block().
 */
function ymb_preprocess_block(&$variables) {
  if ($variables['block']->module === 'ymb') {
    $variables['classes_array'][] = drupal_html_class('block-ymb');
  }
}
